export enum EEnvKey {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  HOST_ADDRESS = 'HOST_ADDRESS',

  SWAGGER_PATH = 'SWAGGER_PATH',
  SWAGGER_IS_PUBLIC = 'SWAGGER_IS_PUBLIC',
  SWAGGER_HOST = 'SWAGGER_HOST',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESC = 'SWAGGER_DESC',

  LOG_LEVEL = 'LOG_LEVEL',

  MONGO_URI = 'MONGO_URI',

  KAFKA_URI = 'KAFKA_URI',
  KAFKA_GROUP_ID = 'distributed_images',
  KAFKA_CLIENT_ID = 'distributed_images_client',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DB = 'REDIS_DB',

  SENTRY_DSN = 'SENTRY_DSN',
  SENTRY_DSN_DEBUG = 'SENTRY_DSN_DEBUG',
  SENTRY_DSN_ENABLED = 'SENTRY_DSN_ENABLED',

  RPC_BSC_TESTNET_URL = 'RPC_BSC_TESTNET_URL',
  CONTRACT_ADDRESS = 'CONTRACT_ADDRESS',
  START_BLOCK = 'START_BLOCK',
  OWNER_PRIVATE_KEY = 'OWNER_PRIVATE_KEY',
  CRAWL_LATEST = 'CRAWL_LATEST',

  GRPC_LEARNING_SERVER_HOST = 'GRPC_LEARNING_SERVER_HOST',

  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',

  IPFS_HOST = 'IPFS_HOST',

  PITANA_API_KEY = 'PITANA_API_KEY',
  PITANA_API_SECRET = 'PITANA_API_SECRET',
  PITANA_JWT = 'PITANA_JWT',
  NFT_STORAGE_KEY = 'NFT_STORAGE_KEY',

  USE_LOCAL_IPFS = 'USE_LOCAL_IPFS',
}
